baseurl = "https://timi.netlify.com/"
languageCode = "en-us"
title = "Timi's RStudio Tutorials"
# Define how many pages appear per site
paginate = 10
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "Aleksa Timilic"
    site_description = "The awesome blog of John Doe."
    location = "Mercyhurst University"
    # Link custom assets relative to /static
    avatar = "img/Timi.jpg"
    header_background = "img/Zante.jpg"
    header_title = "Timi's RStudio Tutorials"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = "aleksatimilic"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = "timilic.a/?hl=sr"
    github    = "Timilic"
    gplus     = ""
